#!/bin/sh

if [ ! -e $HOME/.janus/vim-auto-save ]; then
  git clone https://github.com/907th/vim-auto-save.git $HOME/.janus/vim-auto-save
fi

if [ ! -e $HOME/.janus/vim-multiple-cursors ]; then
  git clone https://github.com/terryma/vim-multiple-cursors $HOME/.janus/vim-multiple-cursors
fi

if [ ! -e $HOME/.janus/vim-commentary ]; then
  git clone https://github.com/tpope/vim-commentary.git $HOME/.janus/vim-commentary
fi

if [ ! -e $HOME/.janus/vim-airline ]; then
  git clone https://github.com/bling/vim-airline.git $HOME/.janus/vim-airline
fi

if [ ! -e $HOME/.janus/vimux ]; then
  git clone https://github.com/benmills/vimux.git $HOME/.janus/vimux
fi

if [ ! -e $HOME/.janus/vim-turbux ]; then
  git clone https://github.com/jgdavey/vim-turbux.git $HOME/.janus/vim-turbux
fi

if [ ! -e $HOME/.janus/vim-gitgutter ]; then
  git clone https://github.com/airblade/vim-gitgutter.git $HOME/.janus/vim-gitgutter
fi

