#!/bin/sh
set -e
dir="`git rev-parse --show-toplevel`"
trap 'rm -f "$dir/.$$.tags"' EXIT
ctags -R --tag-relative --extra=+f -f"$dir/.$$.tags" --languages=-javascript,sql
mv "$dir/.$$.tags" "$dir/.tags"
